Mirror superagent behaviour in call back for creating errors
luispabon/superagent-retry-delay pull request #14
Opened 2023-10-19 19:17 UTC by repl-mike-roest

In our use of this delay module we noticed a different in our end callback behaviour when just including the retry-delay.  This is porting https://github.com/ladjs/superagent/blob/master/src/node/index.js#L893-L908 this section of the core superagent callback into the retry-delay callback to synthize errors on a non-ok response.

2023-10-23 12:22 UTC, repl-mike-roest commented
@luispabon any chance to get this merged?

Thanks

2023-10-23 12:50 UTC, luispabon commented
Thank you Mike. This significantly changes the error handling interface, I'd need to issue a new major version to ensure semver is respected. Could you please let me know which version of superagent you at?

2023-10-23 12:51 UTC, luispabon commented on src/index.js
> +      err.status = err.status || (res ? res.status : undefined);
Looks like these are not covered by tests, could you please write a test to check for this? see https://app.codecov.io/gh/luispabon/superagent-retry-delay/pull/14

2023-10-23 12:52 UTC, luispabon requested changes

2023-10-23 12:52 UTC, luispabon commented on src/index.js
> +      this.emit("error", err);
Looks like this line is not covered by tests, could you please write a test to check for this outcome? see https://app.codecov.io/gh/luispabon/superagent-retry-delay/pull/14

2023-10-23 12:52 UTC, luispabon commented on src/index.js
> +      err.status = err.status || (res ? res.status : undefined);
Looks like these two lines are not covered by tests, could you please write a test to check for this outcome? see https://app.codecov.io/gh/luispabon/superagent-retry-delay/pull/14

2023-10-23 13:10 UTC, repl-mike-roest commented
> Thank you Mike. This significantly changes the error handling interface, I'd need to issue a new major version to ensure semver is respected. Could you please let me know which version of superagent you at?

We were on 3.6.0 and I also tried it on 8.1.2 they both appear to have the same error synthesizing behaviour on nonOk responses.

2023-10-30 13:34 UTC, repl-mike-roest commented
@luispabon sorry to be a pain, just wondering if you have a rough idea of when you would have time to get this in?

Thanks

2023-11-02 14:16 UTC, luispabon approved these changes

2023-11-02 14:16 UTC, merged

2023-11-02 14:26 UTC, luispabon commented
https://github.com/luispabon/superagent-retry-delay/actions/runs/6733950566 <-- published 3.0.0

2023-11-02 16:16 UTC, repl-mike-roest commented
> https://github.com/luispabon/superagent-retry-delay/actions/runs/6733950566 <-- published 3.0.0

You rock thanks so much!

2023-11-02 17:47 UTC, luispabon commented
No, thanks for your contribution 👍🏽